name: verifyer
on: [pull_request, workflow_dispatch]
jobs:
  multi_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install cpputest and lcov ...
        run: |
          sudo apt install --no-install-recommends -y cpputest lcov
          sudo pip install junit2html

      - name: Clone adaptabuild
        run: |
          echo PWD is $PWD
          git submodule update --init
#          git clone https://github.com/rhempel/adaptabuild.git ${HOME}/work/umm_malloc/umm_malloc/adaptabuild

      - name: Run the unit tests
        run: |
          make -f ${HOME}/work/umm_malloc/umm_malloc/adaptabuild_config.mak MCU=host PRODUCT=default unittest
          make -f ${HOME}/work/umm_malloc/umm_malloc/adaptabuild_config.mak MCU=host PRODUCT=enable_info unittest
          make -f ${HOME}/work/umm_malloc/umm_malloc/adaptabuild_config.mak MCU=host PRODUCT=enable_critical_depth_check unittest
          make -f ${HOME}/work/umm_malloc/umm_malloc/adaptabuild_config.mak MCU=host PRODUCT=enable_inline_metrics unittest
          make -f ${HOME}/work/umm_malloc/umm_malloc/adaptabuild_config.mak MCU=host PRODUCT=enable_integrity_check unittest
          make -f ${HOME}/work/umm_malloc/umm_malloc/adaptabuild_config.mak MCU=host PRODUCT=enable_poison_check unittest
          make -f ${HOME}/work/umm_malloc/umm_malloc/adaptabuild_config.mak MCU=host PRODUCT=enable_first_fit unittest
          make -f ${HOME}/work/umm_malloc/umm_malloc/adaptabuild_config.mak MCU=host PRODUCT=default unittest

      - name: Archive test and coverage results
        uses: actions/upload-artifact@main
        with:
          name: Test and Coverage Results
          path: ~/work/umm_malloc/umm_malloc/artifacts
